<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>trio</string>
	</array>
	<key>name</key>
	<string>Trio</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^class)\ ([A-Z][A-Za-z0-9]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter_round</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#visible</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#temporaldomain</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#domains</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#connections</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#items</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#item_def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#event_state</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#axioms</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#vars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formulae</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#capName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>axioms</key>
		<dict>
			<key>match</key>
			<string>(axioms\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>capName</key>
		<dict>
			<key>match</key>
			<string>([A-Z][A-Za-z0-9]*)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>(\/\*)</string>
			<key>comment</key>
			<string>comment block</string>
			<key>end</key>
			<string>(\*\/)</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>comment</key>
			<string>comment line</string>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment.line.lol</string>
		</dict>
		<key>connections</key>
		<dict>
			<key>match</key>
			<string>(connections\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>definition</key>
		<dict>
			<key>begin</key>
			<string>([a-z][A-Za-z0-9]*\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#trio</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#capName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter_square</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric_domain</string>
				</dict>
			</array>
		</dict>
		<key>domains</key>
		<dict>
			<key>match</key>
			<string>(domains\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([A-Za-z0-9]+)</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
			</array>
		</dict>
		<key>event_state</key>
		<dict>
			<key>begin</key>
			<string>((event)|(state))(\ )+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#capName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rpar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>formulae</key>
		<dict>
			<key>match</key>
			<string>(formulae\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized</string>
		</dict>
		<key>import</key>
		<dict>
			<key>begin</key>
			<string>(import)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#capName</string>
				</dict>
			</array>
		</dict>
		<key>item_def</key>
		<dict>
			<key>begin</key>
			<string>((TD\ total)|(TI\ total))(\ )+([a-z][A-Za-z0-9]*)(\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#capName</string>
				</dict>
			</array>
		</dict>
		<key>items</key>
		<dict>
			<key>match</key>
			<string>(items\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>modules</key>
		<dict>
			<key>match</key>
			<string>(modules\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>nCapName</key>
		<dict>
			<key>match</key>
			<string>([a-z][A-Za-z0-9]*)</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>([0-9]+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>numeric_domain</key>
		<dict>
			<key>match</key>
			<string>([0-9]+)..([0-9]+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>parameter_round</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(const)</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
			</array>
		</dict>
		<key>parameter_square</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(is\ const)</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Za-z0-9]+)</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
			</array>
		</dict>
		<key>rpar</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#capName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
			</array>
		</dict>
		<key>signature</key>
		<dict>
			<key>match</key>
			<string>(signature\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>temporaldomain</key>
		<dict>
			<key>begin</key>
			<string>(temporal\ domain\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
			</array>
		</dict>
		<key>trio</key>
		<dict>
			<key>match</key>
			<string>(\&lt;)|(\&gt;)|(\-\&gt;)|(\&lt;\-\&gt;)|(\=)|(\&amp;)|(\|)|(Dist)|(Futr)|(Past)|(Lasts)|(Lasted)|(Since)|(AlwP)|(AlwF)|(Alw)|(SomP)|(SomF)|(Som)|(WithinP)|(WithinF)|(UpToNow)|(Becomes)|(NextTime)|(Until)|(Since)</string>
			<key>name</key>
			<string>support.type</string>
		</dict>
		<key>vars</key>
		<dict>
			<key>match</key>
			<string>(vars\:)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>visible</key>
		<dict>
			<key>begin</key>
			<string>(visible\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nCapName</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.trio</string>
	<key>uuid</key>
	<string>f2932f90-87dd-439e-9e78-6ed24e413724</string>
</dict>
</plist>
